### ISSUE TITLE
version `GLIBC_2.29' not found (required by box64)

### ISSUE THREAD

**Issue by Botspot** [ryanfortner/box64-debs#1]
This is on Raspberry Pi OS Buster. Am I missing a dependency?
```
pi@raspberrypi:~ $ sudo apt update && sudo apt install box64 -y
Get:1 https://ryanfortner.github.io/box64-debs/debian ./ InRelease [2,115 B]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Get:4 http://deb.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:5 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:6 https://ryanfortner.github.io/box64-debs/debian ./ Packages [1,016 B]
Get:7 http://deb.debian.org/debian buster/main armhf Packages [7,698 kB]
Get:8 http://deb.debian.org/debian buster/main arm64 Packages [7,735 kB]
Get:9 http://deb.debian.org/debian buster/main Translation-en [5,968 kB]
Get:10 http://deb.debian.org/debian buster/contrib armhf Packages [40.1 kB]
Get:11 http://deb.debian.org/debian buster/contrib arm64 Packages [38.4 kB]
Get:12 http://deb.debian.org/debian buster/non-free armhf Packages [62.1 kB]
Get:13 http://deb.debian.org/debian buster/non-free arm64 Packages [53.9 kB]
Get:14 http://deb.debian.org/debian buster/non-free Translation-en [88.8 kB]
Fetched 21.9 MB in 12s (1,845 kB/s)                                            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
119 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.10' to '10.11'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  box64
0 upgraded, 1 newly installed, 0 to remove and 119 not upgraded.
Need to get 1,367 kB of archives.
After this operation, 7,709 kB of additional disk space will be used.
Get:1 https://ryanfortner.github.io/box64-debs/debian ./ box64 0.1.5+20211005.348cb572-1 [1,367 kB]
Fetched 1,367 kB in 0s (3,817 kB/s)
Selecting previously unselected package box64.
(Reading database ... 91979 files and directories currently installed.)
Preparing to unpack .../box64_0.1.5+20211005.348cb572-1_arm64.deb ...
Unpacking box64 (0.1.5+20211005.348cb572-1) ...
Setting up box64 (0.1.5+20211005.348cb572-1) ...
Restarting systemd-binfmt...
pi@raspberrypi:~ $ box64
box64: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by box64)
```

**Comment by ryanfortner** [comment]
The box64 debs in this repository have been compiled on Debian 11 Bullseye, which has a glibc version that is higher than that of Debian Buster. 

As a result, they'll only work on Bullseye.

**Comment by Botspot** [comment]
Could you use a buster chroot or something?

**Comment by ryanfortner** [comment]
> Could you use a buster chroot or something?

I could add another package, like 'box64-buster'. However I'm away for the weekend so I won't be able to until Monday.

**Comment by Botspot** [comment]
> I could add another package, like 'box64-buster'.

I don't see the need for a name-change, as a package for Buster should work fine for Bullseye.

**Comment by ryanfortner** [comment]
Makes sense. I'll make a chroot on Monday.

**Comment by ryanfortner** [comment]
@Botspot I've set up a buster chroot and run my script, could you try re-installing box64 now?

**Comment by Botspot** [comment]
> @Botspot I've set up a buster chroot and run my script, could you try re-installing box64 now?

It works now!
BTW, have you ever used my [vdesktop](https://github.com/Botspot/vdesktop) tool? It is a great resource to test applications in other Raspbian environments, without having to setup multi-boot or to deal with multiple SD cards.
On my 32-bit Buster system, I use vdesktop to test apps on Stretch, Twister, Bullseye, and 64-bit RPiOS.

**Comment by Botspot** [comment]
Feel free to open a PR on Pi-Apps to switch to your Box64 debs.

**Comment by ryanfortner** [comment]
> BTW, have you ever used my [vdesktop](https://github.com/Botspot/vdesktop) tool? It is a great resource to test applications in other Raspbian environments, without having to setup multi-boot or to deal with multiple SD cards.
> 
> On my 32-bit Buster system, I use vdesktop to test apps on Stretch, Twister, Bullseye, and 64-bit RPiOS.

Yes, I use it often to test 64-bit apps for my repo, quite a useful tool!

> Feel free to open a PR on Pi-Apps to switch to your Box64 debs.

Will do, thanks 🤝

**Comment by Botspot** [comment]
> Yes, I use it often to test 64-bit apps for my repo, quite a useful tool!

What I meant was: in this case vdesktop allows you to test a working Buster system, from inside your Bullseye system.
