### ISSUE TITLE
Box64 for other ARM64 64bits Linux platform like termux with -DBAD_SIGNAL=ON

### ISSUE THREAD

**Issue by xDoge26** [ryanfortner/box64-debs#13]

**Comment by xDoge26** [comment]
https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md#for-other-arm64-linux-platforms

**Comment by ryanfortner** [comment]
See https://github.com/ryanfortner/box86-debs/issues/2#issuecomment-1474594610 , same thing applies to this repo
