### ISSUE TITLE
Error running apt update after adding repository to sources.list.d

### ISSUE THREAD

**Issue by kylhill** [ryanfortner/box64-debs#16]
I am unable to get the Repository Installation instructions to work.  After adding the source according to the instructions on this repo:
```
sudo wget https://ryanfortner.github.io/box64-debs/box64.list -O /etc/apt/sources.list.d/box64.list
wget -qO- https://ryanfortner.github.io/box64-debs/KEY.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/box64-debs-archive-keyring.gpg 
sudo apt update && sudo apt install box64-rpi4arm64 -y
```
I get the following error when running apt update:
```
Get:4 https://box64.debian.ryanfortner.dev/debian ./ InRelease [2115 B]
Err:4 https://box64.debian.ryanfortner.dev/debian ./ InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7759FA1D9FECAC9E
Reading package lists...
GPG error: https://box64.debian.ryanfortner.dev/debian ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7759FA1D9FECAC9E
E: The repository 'https://ryanfortner.github.io/box64-debs/debian ./ InRelease' is not signed.\"
```

**Comment by ryanfortner** [comment]
That's odd. The line with gpg is supposed to take care of adding the gpg key and prevent this issue. 

Does the /etc/apt/trusted.gpg.d directory actually exist on your system? If so, are there any files in it?

**Comment by kylhill** [comment]
It contains the "box64-debs-archive-keyring.gpg" along with the other debian source keyrings.  I've attached a zipped copy of the file. (to work around github limitations)
[box64-debs-archive-keyring.zip](https://github.com/ryanfortner/box64-debs/files/11124871/box64-debs-archive-keyring.zip)

**Comment by kylhill** [comment]
gpg prints the following:
```
gpg --show-keys box64-debs-archive-keyring.gpg
pub   rsa4096 2021-07-11 [SC]
      DF9A1B8523C32EEEFF2A6CDA7759FA1D9FECAC9E
uid                      Ryan Fortner <pinetmedia@gmail.com>
sub   rsa4096 2021-07-11 [E]
```

**Comment by kylhill** [comment]
I can no longer reproduce this issue.  I assume it was a stale build environment.

**Comment by Sean-Zeo** [comment]
Issue occuring on my end also
