### ISSUE TITLE
Use ARM64 target instead of GENERIC_ARM

### ISSUE THREAD

**Issue by xDoge26** [ryanfortner/box64-debs#20]
https://github.com/ptitSeb/box64/blob/c7e0ba82b4a586fed8f4d45acd0c774ddf0f777b/CMakeLists.txt#L22

**Comment by ryanfortner** [comment]
fixed with commit https://github.com/ryanfortner/box64-debs/commit/7c24be625e0e65b189f269131690ddd375473aae, thanks
