### ISSUE TITLE
Build for qualcom kryo?

### ISSUE THREAD

**Issue by castaway** [ryanfortner/box64-debs#22]
Qualcomm® Kryo™ 468 Octa-core 2.10 GHz

Mine is an acer spin 513 (cp513-1h) which apparently has a qualcomm processor.

**Comment by ryanfortner** [comment]
I'm not seeing any processor-specific [build flag](https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md) for this system. You'll need to open an issue on the source box64 repository.

In the meantime, maybe try the generic arm64 build `box64-arm64`?
