### ISSUE TITLE
Apt won't install latest rpi4 build

### ISSUE THREAD

**Issue by tristanmorgan** [ryanfortner/box64-debs#25]
Hi, I'm trying to install the latest build of box64-rpi4arm64 within a Docker container and it appears the latest available is `0.2.5+20231025.12c40a5-1` (as of writing this issue the latest should be `0.2.5+20231205.24f241a-1`). I guess the [Packages](https://box64.debian.ryanfortner.dev/debian/Packages) file isn't up to date.

my Dockerfile used the following to install box64

```dockerfile
ADD https://ryanfortner.github.io/box64-debs/box64.list /etc/apt/sources.list.d/box64.list
ADD https://ryanfortner.github.io/box64-debs/KEY.gpg /tmp/KEY.gpg
RUN cat /tmp/KEY.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/box64-debs-archive-keyring.gpg \
 && apt-get update 
 && apt-get install box64-rpi4arm64 -y 
```

and debugging shows the old package in apt
```bash
# apt policy box64-rpi4arm64
box64-rpi4arm64:
  Installed: 0.2.5+20231025.12c40a5-1
  Candidate: 0.2.5+20231025.12c40a5-1
  Version table:
 *** 0.2.5+20231025.12c40a5-1 500
        500 https://ryanfortner.github.io/box64-debs/debian ./ Packages
        100 /var/lib/dpkg/status
     0.2.5+20231024.65fc95b-1 500
        500 https://ryanfortner.github.io/box64-debs/debian ./ Packages
     0.2.5+20231023.b3daf55-1 500
        500 https://ryanfortner.github.io/box64-debs/debian ./ Packages
```

Thanks for providing these packages.

T.

**Comment by ryanfortner** [comment]
I just took a look and it seems that the packages are building just fine, and all files are up to date, however, the GitHub Pages action (which publishes the builds to the website) has been failing due to a `no space left on device` error. 

I've found a [potential solution](https://github.com/jlumbroso/free-disk-space) for the issue, but unfortunately I'm slammed with other tasks and likely won't be able to get to it until the weekend.

**Comment by tristanmorgan** [comment]
Thanks for running all of this. Would it help to prune some older builds? Maybe all builds for a month, once a week for older... or are you trying to preserve all builds?

**Comment by ryanfortner** [comment]
You're right, that's probably a better idea. I've removed all builds from before July 2023. If someone finds that they need a build from that time, they can check out the commit of when that build was pushed.

I'll probably also implement yearly pruning in the github actions.
