### ISSUE TITLE
Add RASPI5 Building

### ISSUE THREAD

**Issue by ghost** [ryanfortner/box64-debs#26]
Box64 now supports raspi5 builds (for more info see [here](https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md#for-raspberry-pi-5)

**Comment by DuncanMillard** [comment]
+1 - in particular it would be great if you could add two RPI5 versions: one with 4K page size and one with 16K as it looks like both options are supported by box64.

(At the moment box64 doesn't work on my RPI5 8Gb, it fails with "Error: PageSize configuration is wrong: configured with 4096, but got 16384")

**Comment by ryanfortner** [comment]
Implemented with commit https://github.com/ryanfortner/box64-debs/commit/cf1972b29f80d19dbdbbe21a63476795f1cc289a, new packages are building and will be uploaded shortly

**Comment by ghost** [comment]
👍

**Comment by DuncanMillard** [comment]
Thanks for this @ryanfortner  - I've successfully used the 16kb page size version to get the MS Minecraft Bedrock server image running on my Pi5. Very much appreciated.
