### ISSUE TITLE
Generic package box64-arm64 seems to have gone missing

### ISSUE THREAD

**Issue by itzg** [ryanfortner/box64-debs#35]
The box64-arm64 package was here

https://github.com/ryanfortner/box64-debs/tree/8b7db72a583eb1c54c42c6bb5674126b8d2c6d08/debian

came and went with odd version identifiers, and then has been gone since this 

https://github.com/ryanfortner/box64-debs/tree/28b43fc8b742d72e4205543d9662318c88e20cbf/debian

Is there an alternative you recommend as as "generic" arm64 variant to use.

**Comment by ryanfortner** [comment]
Thanks for letting me know, I'm working on this now. I think it has to do with box64 internals changing in such a way that was messing with the way the script fetches the version string.

**Comment by ryanfortner** [comment]
I made a few changes to the scripts and everything is working fine now. 

Please note that I also changed the generic ARM64 target package name to simply `box64`. This has been requested by users in the past and I finally came around to changing it, so please modify your docker project as needed.

**Comment by itzg** [comment]
Thanks!
